# Generated by Django 3.2 on 2021-05-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=32)),
                ('identity_card_no', models.CharField(max_length=32, unique=True)),
                ('department', models.CharField(choices=[('Department of Internal Medicine', '内科'), ('Department of Surgery', '外科'), ('Department of Pediatrics', '儿科'), ('Department of Obstetrics and Gynecology', '妇产科'), ('Department of Traditional Chinese Medicine', '中医科'), ('Department of Dermatology', '皮肤科'), ('Department of Oral Medicine', '口腔科')], max_length=64)),
                ('title', models.CharField(choices=[('director physician', '主任医师'), ('assistant director physician', '副主任医师'), ('physician', '医师')], max_length=64)),
                ('description', models.TextField(default='暂无简介', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=32)),
                ('identity_card_no', models.CharField(max_length=32, unique=True)),
                ('medical_insurance', models.BooleanField()),
                ('telephone_no', models.CharField(max_length=32)),
                ('birth_date', models.DateField()),
                ('register_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
