# Generated by Django 3.2 on 2021-05-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0005_alter_medicinerequest_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=32)),
                ('identity_card_no', models.CharField(max_length=32, unique=True)),
                ('department', models.CharField(choices=[('Laboratory', '化验室'), ('X-ray Room', 'X光室'), ('Cystoscopy Room', '膀胱镜室'), ('Gastroscope Room', '胃镜室')], max_length=64)),
                ('title', models.CharField(choices=[('director physician', '主任医师'), ('assistant director physician', '副主任医师'), ('physician', '医师')], max_length=64)),
                ('description', models.TextField(default='暂无简介', max_length=500)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
