# Generated by Django 3.2 on 2021-05-28 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0007_auto_20210528_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
