# Generated by Django 3.2 on 2021-06-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0008_auto_20210528_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Department of Internal Medicine', '内科'), ('Department of Surgery', '外科'), ('Department of Pediatrics', '儿科'), ('Department of Obstetrics and Gynecology', '妇产科'), ('Department of Traditional Chinese Medicine', '中医科'), ('Department of Dermatology', '皮肤科'), ('Department of Oral Medicine', '口腔科')], max_length=64),
        ),
    ]
