# Generated by Django 3.2 on 2021-06-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0009_alter_doctor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_inspector',
        ),
    ]
